export const AUTO_PILOT_GLOBAL_STAGES = new Set([
  'started',
  'round_started',
  'product_started',
  'flow_home_before_product',
  'delay_between_products',
  'cleanup_latest_project',
  'completed',
  'stopped',
  'error',
]);

export const AUTO_PILOT_STAGE_LABELS: Record<string, string> = {
  started: 'เตรียมเปิด Flow',
  round_started: 'เริ่มรอบใหม่',
  product_started: 'เลือกสินค้า',
  delay_between_products: 'หน่วงเวลาสินค้าถัดไป',
  step_started: 'เริ่มสร้างงาน',
  open_project: 'เปิดโปรเจกต์',
  flow_newProject: 'เปิดโปรเจกต์',
  flow_deleteLatestProject: 'ลบโปรเจกต์ล่าสุด',
  flow_home_before_product: 'เปิด Flow หลัก',
  flow_language_error: 'ตรวจภาษา Flow',
  wait_flow_ready: 'รอ Flow พร้อม',
  refresh_before_config: 'รีเฟรช Flow',
  multi_scene_refresh_image: 'รีเฟรช Flow',
  multi_scene_refresh_video: 'รีเฟรช Flow',
  voiceover_video_retry_refresh: 'รีเฟรช Flow',
  configure_flow: 'ตั้งค่า Flow',
  flow_configurePopper: 'ตั้งค่า Flow',
  flow_selectRecentImage: 'เลือกรูปล่าสุด',
  flow_uploadReferenceImage: 'อัปโหลดรูปอ้างอิง',
  flow_ensureVideoReferenceAttached: 'ตรวจ reference',
  flow_fillPrompt: 'กรอก Prompt',
  flow_submit: 'ส่งคำสั่งสร้างแล้ว',
  flow_reusePromptAndSubmit: 'Reuse Prompt',
  flow_videoSnapshot: 'บันทึกสถานะเดิม',
  flow_videoResults: 'ตรวจผลจาก Flow',
  flow_downloadImages: 'ดาวน์โหลดรูป',
  flow_downloadVideo: 'ดาวน์โหลดวิดีโอ',
  single_step_retry_config: 'ตั้งค่า Retry',
  multi_scene_config_image: 'ตั้งค่ารูปฉาก',
  multi_scene_config_video: 'ตั้งค่าวิดีโอฉาก',
  voiceover_video_retry_config: 'ตั้งค่า Retry ภาพล้วน',
  attach_reference: 'แนบรูปอ้างอิง',
  multi_scene_attach_reference: 'แนบรูปอ้างอิง',
  multi_scene_attach_previous_image: 'แนบรูปอ้างอิง',
  upload_reference: 'แนบรูปอ้างอิง',
  ensure_video_reference: 'ตรวจ reference',
  upload_reference_retry: 'Retry อัปโหลดรูป',
  multi_scene_start: 'เริ่มหลายฉาก',
  multi_scene_capture_prior_image: 'ดึงรูปตั้งต้น',
  multi_scene_image: 'สร้างรูปฉาก',
  multi_scene_prepare_prompts: 'AI คิดบท',
  multi_scene_dialogue_ready: 'ได้บทพูด',
  multi_scene_video: 'สร้างวิดีโอฉาก',
  multi_scene_select_recent_reference: 'เลือกรูปล่าสุด',
  multi_scene_upload_reference_fallback: 'อัปโหลดรูปแทน',
  fill_prompt: 'กรอก Prompt',
  submitted: 'ส่งคำสั่งสร้างแล้ว',
  submit_start_check: 'ตรวจหลัง Submit',
  waiting_start: 'รอ Flow เริ่ม',
  submit_wait_without_retry: 'รอ Flow เริ่ม',
  submit_wait_after_retype: 'รอ Flow เริ่ม',
  retype_prompt_retry: 'Retype Prompt',
  retype_submitted: 'ส่งหลัง Retype',
  retype_start_check: 'ตรวจหลัง Retype',
  single_step_retry: 'Retry งานเดี่ยว',
  single_step_reuse_prompt: 'Reuse Prompt',
  single_step_ai_rewrite: 'AI Rewrite',
  single_step_retry_refresh: 'รีเฟรช Retry',
  single_step_retry_fill_prompt: 'กรอก Prompt ซ้ำ',
  single_step_retry_submitted: 'ส่ง Retry แล้ว',
  waiting_result: 'รอผลจาก Flow',
  waiting_result_settle: 'รอ Preview',
  downloading_result: 'กำลังดาวน์โหลด',
  download_triggered: 'รับไฟล์จาก Flow',
  generated: 'ได้ไฟล์',
  scene_video_ready: 'ได้วิดีโอฉาก',
  voiceover_video_retry: 'Retry ภาพล้วน',
  flow_failed_detected: 'Flow แจ้งล้มเหลว',
  voiceover_probe_videos: 'ตรวจความยาวจริง',
  voiceover: 'สร้างเสียงพากย์',
  merge_video: 'รวมวิดีโอ',
  multi_scene_done: 'เสร็จหลายฉาก',
  failed: 'สร้างไม่สำเร็จ',
  download_missing: 'ยังไม่พบไฟล์ดาวน์โหลด',
  cleanup_latest_project: 'ลบโปรเจกต์ล่าสุด',
  completed: 'เสร็จแล้ว',
  stopped: 'หยุดแล้ว',
  error: 'ผิดพลาด',
};

export function getAutoPilotStageLabel(stage: string | null | undefined, fallback = 'รอเริ่มงาน'): string {
  if (!stage) return fallback;
  return AUTO_PILOT_STAGE_LABELS[stage] ?? stage.replace(/^flow_/, '');
}

export function isAutoPilotGlobalStage(stage: string | null | undefined): boolean {
  return Boolean(stage && AUTO_PILOT_GLOBAL_STAGES.has(stage));
}
